name: omericoramos.tech CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 checkout do repositorio
        uses: actions/checkout@v1

      - name: 📂 fazendo o deploy churchHub
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          TARGET: ${{secrets.REMOTE_TARGET}}
          exclude: |
            /public/build/**
            /vendor/**
            /node_modules/**
            /bootstrap/**
            /storage/framework/**
            /storage/log/**
            /.git/**
            .env
